### ISSUE TITLE
Needs update for upcoming Pod Security Standard `restricted`

### ISSUE THREAD

**Issue by AlexanderBrevig** [entur/mummu#120]
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

`securityContext` is no longer optional

```yaml
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test
              # ...
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop: ["ALL"]
                seccompProfile:
                  type: RuntimeDefault
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
```
